#!/bin/bash


COMMIT=${1:-master}
BASEDIR=${2:-$(pwd)}
CONTAINER=$(basename $BASEDIR)
CONTTYPE=debug
DOCKEROUT=${HOME}/dockerout/fbneo/${CONTTYPE}

[ ! -d ${DOCKEROUT} ] && mkdir -p ${DOCKEROUT}

docker stop $CONTAINER-${CONTTYPE}
docker rm $CONTAINER-${CONTTYPE}

# launch new
docker run -d \
--volume ${DOCKEROUT}:/home/emudev \
--name ${CONTAINER}-${CONTTYPE} \
-e RELEASE=0 \
-e COMMIT=${COMMIT} \
$CONTAINER:latest

#docker logs --follow ${CONTAINER}-${CONTTYPE}

