#!/bin/bash


COMMIT=${1:-master}
BASEDIR=${2:-$(pwd)}
CONTAINER=$(basename $BASEDIR)
DOCKEROUT=${HOME}/dockerout/fbneo/normal

[ ! -d ${DOCKEROUT} ] && mkdir -p ${DOCKEROUT}

docker stop $CONTAINER
docker rm $CONTAINER

# launch new
docker run -d \
--volume ${DOCKEROUT}:/home/emudev \
--name $CONTAINER \
-e RELEASE=1 \
-e COMMIT=${COMMIT} \
$CONTAINER:latest

docker logs --follow $CONTAINER
